require "application_system_test_case"

class MinuteBooksTest < ApplicationSystemTestCase
  setup do
    @minute_book = minute_books(:one)
  end

  test "visiting the index" do
    visit minute_books_url
    assert_selector "h1", text: "Minute Books"
  end

  test "creating a Minute book" do
    visit minute_books_url
    click_on "New Minute Book"

    fill_in "Community", with: @minute_book.community_id
    fill_in "Date", with: @minute_book.date
    fill_in "File", with: @minute_book.file
    fill_in "Generated By", with: @minute_book.generated_by
    fill_in "Notes", with: @minute_book.notes
    click_on "Create Minute book"

    assert_text "Minute book was successfully created"
    click_on "Back"
  end

  test "updating a Minute book" do
    visit minute_books_url
    click_on "Edit", match: :first

    fill_in "Community", with: @minute_book.community_id
    fill_in "Date", with: @minute_book.date
    fill_in "File", with: @minute_book.file
    fill_in "Generated By", with: @minute_book.generated_by
    fill_in "Notes", with: @minute_book.notes
    click_on "Update Minute book"

    assert_text "Minute book was successfully updated"
    click_on "Back"
  end

  test "destroying a Minute book" do
    visit minute_books_url
    page.accept_confirm do
      click_on "Destroy", match: :first
    end

    assert_text "Minute book was successfully destroyed"
  end
end
